spring:
  application:
    name: api-customer
  datasource:
    url: jdbc:h2:file:~/customerbanking;DB_CLOSE_ON_EXIT=FALSE;
    jpa:
      hibernate:
        ddl-auto: update
      properties:
        hibernate:
          show_sql: true
    h2:
      console:
        enable: true
        settings:
          web-allow-others: true

server:
  port: 6061

eureka:
  client:
    service-url:
      default-zone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: true
logging:
  file: customer.log
  level:
    root:
    project:
      user:
        UserClient: FULL
